apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: the-container
        image: gcr.io/gcp-study-192807/github-kheiakiyama-gke-pubsub-sample-subscriber@master
        ports:
        - containerPort: 3000
