apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      volumes:
      - name: google-cloud-key-subscriber
        secret:
          secretName: subscriber-key
      containers:
      - name: the-container
        image: gcr.io/gcp-study-192807/github-kheiakiyama-gke-pubsub-sample-subscriber:master
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key-subscriber
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        ports:
        - containerPort: 3000
